name: aws-iot-greengrass
version: '2.16.0'
summary: AWS IoT Core and Greengrass v2 configurator
description: A Python application to configure AWS IoT Core things and install Greengrass v2

base: core24
confinement: strict
grade: stable

environment:
  PATH: $SNAP/docker/bin:$PATH
  PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHON_PATH
  JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-arm64

layout:
  /etc/ssl/certs/java:
    bind: $SNAP/etc/ssl/certs/java

plugs:
  docker-executables:
    interface: content
    content: docker-executables
    target: $SNAP/docker
    default-provider: docker

slots:
  shared-files:
    interface: content
    content: shared-files
    source:
      read:
        - $SNAP/shared

apps:
  configure:
    command: bin/python3 $SNAP/bin/iot-greengrass-setup.py
    plugs: 
      - network
      - network-bind
      - home
      - system-observe
      - mount-observe
      - hardware-observe
      - process-control
      - docker-executables
      - docker
      - camera
    slots:
      - shared-files

  bootstrap:
    command: bin/python3 $SNAP/bin/iot-greengrass-bootstrap.py
    plugs:
      - network
      - network-bind
      - home
      - system-observe
      - mount-observe
      - hardware-observe
      - process-control
      - docker-executables
      - docker
      - camera
    slots:
      - shared-files

  greengrass-daemon:
    command: bin/greengrass-wrapper.sh
    daemon: simple
    restart-condition: always
    restart-delay: 10s
    plugs:
      - network
      - network-bind
      - home
      - system-observe
      - mount-observe
      - hardware-observe
      - process-control
      - docker-executables
      - docker
      - camera
    slots:
      - shared-files

parts:
  iot-greengrass-app:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    stage-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-11-jre-headless
    build-packages:
      - wget
    override-build: |
      # Run default Python plugin build first
      craftctl default

      # Create directory and download Greengrass installer
      mkdir -p $CRAFT_PART_INSTALL/opt/greengrass
      wget -O $CRAFT_PART_INSTALL/opt/greengrass/greengrass-nucleus.zip \
        https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-2.16.0.zip

      wget -O $CRAFT_PART_INSTALL/opt/greengrass/aws.greengrass.FleetProvisioningByClaim.jar \
        https://d2s8p88vqu9w66.cloudfront.net/releases/aws-greengrass-FleetProvisioningByClaim/fleetprovisioningbyclaim-latest.jar

      # Ensure Python scripts are executable and in correct location
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp local-scripts/iot-greengrass-setup.py $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/iot-greengrass-setup.py

      cp local-scripts/iot-greengrass-bootstrap.py $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/iot-greengrass-bootstrap.py

      cp local-scripts/greengrass-wrapper.sh $CRAFT_PART_INSTALL/bin/
      chmod +x $CRAFT_PART_INSTALL/bin/greengrass-wrapper.sh

      # Copy bootstrap config template
      mkdir -p $CRAFT_PART_INSTALL/etc
      cp bootstrap-config.yaml $CRAFT_PART_INSTALL/etc/bootstrap-config.yaml.template

      mkdir -p $CRAFT_PART_INSTALL/etc/ssl/certs/java
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-arm64/lib/security
      touch $CRAFT_PART_INSTALL/etc/ssl/certs/blacklisted.certs

      rm -f $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-arm64/lib/security/blacklisted.certs
      touch $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-arm64/lib/security/blacklisted.certs
      
      # Remove the external symlink and copy the actual cacerts file
      rm -f $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-arm64/lib/security/cacerts
      cp $CRAFT_PART_INSTALL/etc/ssl/certs/java/cacerts \
        $CRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-arm64/lib/security/cacerts

    organize:
      shared/: shared/