name: aws-greengrass-config # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Greengrass config content interface snap # 79 char long summary
description: GG Suport Snap

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  aws-greengrass-config:
    # See 'snapcraft plugins'
    plugin: dump
    source: local-files

slots:
  greengrass-config-content:
    interface: content
    content: greengrass-config-content
    source: 
      read: 
         - $SNAP/shared-files


