---
system:
  certificateFilePath: "/var/snap/aws-iot-greengrass-v2/current/greengrass/v2/shared-files/gg-certs/device.pem.crt" # absolute path as path relative to this config.yaml file did not work 
  privateKeyPath: "/var/snap/aws-iot-greengrass-v2/current/greengrass/v2/shared-files/gg-certs/private.pem.key"
  rootCaPath: "/var/snap/aws-iot-greengrass-v2/current/greengrass/v2/shared-files/gg-certs/AmazonRootCA1.pem"
  rootpath: "/var/snap/aws-iot-greengrass-v2/current/greengrass/v2"
  thingName: "MyGGCoreCIS"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.4.0"
    configuration:
      awsRegion: "us-west-2"
      iotRoleAlias: "GreengrassCoreTokenExchangeRoleAlias"
      iotDataEndpoint: "a6gwt5c3rk3kl-ats.iot.us-west-2.amazonaws.com"
      iotCredEndpoint: "cfm5sae6kdtaf.credentials.iot.us-west-2.amazonaws.com"
