#!/bin/bash

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Set default value for greengrass config.
# For now, it doesn't matter if this is invalid as user will provide config during setup
#
# See https://github.com/aws-greengrass/aws-greengrass-snap/issues/12
#snapctl set greengrass-config="$HOME/defaultconfig.yaml"
