#!/bin/bash

# TODO: Remove this file altogether

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Set default value for greengrass config.
# For now, it doesn't matter if this is invalid as user will provide config during setup
#snapctl set greengrass-config="$HOME/defaultconfig.yaml"
