#!/bin/bash -ex

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

greengrass_config="$(snapctl get greengrass-config)"
logger "aws-iot-greengrass::configure: validating config file: $greengrass_config"

# TODO: Add correct validation for config file
# Note - the current check only validates that a config file path has
# been specified, which is not considered an 'error', so 'exit 0' is
# used. Future validation logic should a non-zero exit code if a config
# file has been specified which is not valid (e.g. a malformed file).
if [ -z "$greengrass_config" ]; then
  echo "\"$greengrass_config\" is not a valid Greengrass config" >&2
  exit 0 # Fail refresh if greengrass config is invalid
fi

logger "aws-iot-greengrass::post-refresh: re-running installer"
cd "$SNAP_DATA" || exit 1

GG_ROOT="$SNAP_DATA/greengrass/v2"

java -Droot="$GG_ROOT" -Dlog.store=FILE -jar "$SNAP/lib/Greengrass.jar" \
  --start false --component-default-user root:root || exit 2
#--init-config "$greengrass_config" shouldn't need init config

# TODO: rename greengrass to nucleus
logger "aws-iot-greengrass::post-refresh: enabling/starting nucleus!"
snapctl start --enable aws-iot-greengrass-v2.greengrass
