#!/bin/bash -ex

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

logger "aws-iot-greengrass::post-refresh: validating Greengrass root setup"

# Check for existence of the IPC socket to determine
# if greengrass has been installed; GG_ROOT cannot
# be used for this as the config content interface
# uses `$SNAP_DATA/greengrass/v2/shared-files` for a
# target, so GG_ROOT could exist even though the
# installer has not yet been run. If the socket doesn't
# exist, then there's nothing more to do as greengrass
# hasn't yet been 'installed'.
if [ ! -e "$SNAP_DATA/greengrass/v2/ipc.socket" ]; then
  logger "aws-iot-greengrass::post-refresh: Greengrass root is not valid"
  exit 0
fi

# We assume that the configure hook ran and Greengrass root was setup successfully in the past.
# re-run the installer.
logger "aws-iot-greengrass::post-refresh: re-running installer"
cd "$SNAP_DATA" || exit 1

java -Droot="$SNAP_DATA/greengrass/v2" -Dlog.store=FILE -jar "$SNAP/lib/Greengrass.jar" \
  --start false --component-default-user root:root || exit 2

logger "aws-iot-greengrass::post-refresh: end of post-refresh hook!"
